import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Sidebar from "@/components/admin/Sidebar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="md:flex gap-3 w-full container mx-auto">
      <aside>
        <Sidebar />
      </aside>
      
      <main className="w-full">
        {children}
      </main>
    </div>
  );
}
